export * from './explain.api';
import { ExplainApi } from './explain.api';
export * from './explain.apiInterface';
export * from './planningsolution.api';
import { PlanningsolutionApi } from './planningsolution.api';
export * from './planningsolution.apiInterface';
export * from './preset.api';
import { PresetApi } from './preset.api';
export * from './preset.apiInterface';
export const APIS = [ExplainApi, PlanningsolutionApi, PresetApi];
