/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ExplanationRequest } from '../model/models';
import { ExplanationViewModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExplainApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Ask a natural-language question about a planning solution
     * Answers a natural-language question about a planning solution using a GenAI model. The question, the solver constraints and the solution (including its score and constraint matches) are combined into a prompt. Pass the returned conversationId on follow-up questions to keep the conversation context (multi-turn).
     * @param explanationRequest 
     */
    explainPlanningSolution(explanationRequest: ExplanationRequest, extraHttpRequestParams?: any): Observable<ExplanationViewModel>;

}
