/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PlanningSolutionViewModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlanningsolutionApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get the most recent planning solution
     * Returns the newest planning solution including all talks and timeslots.
     */
    getLatestPlanningSolution(extraHttpRequestParams?: any): Observable<PlanningSolutionViewModel>;

    /**
     * Trigger a new planning solution calculation
     * Starts an asynchronous planning solution calculation and returns immediately. The calculation runs in the background and its result can be retrieved later via GET /v1/planningsolution/latest.
     */
    startPlanningSolution(extraHttpRequestParams?: any): Observable<{}>;

}
