/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TalkPresetRequest } from '../model/models';
import { TalkPresetViewModel } from '../model/models';
import { TimeslotPresetRequest } from '../model/models';
import { TimeslotPresetViewModel } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PresetApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new talk preset
     * 
     * @param talkPresetRequest 
     */
    createTalkPreset(talkPresetRequest: TalkPresetRequest, extraHttpRequestParams?: any): Observable<TalkPresetViewModel>;

    /**
     * Create a new timeslot preset
     * 
     * @param timeslotPresetRequest 
     */
    createTimeslotPreset(timeslotPresetRequest: TimeslotPresetRequest, extraHttpRequestParams?: any): Observable<TimeslotPresetViewModel>;

    /**
     * Delete a talk preset
     * 
     * @param id Database id of the preset record
     */
    deleteTalkPreset(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete a timeslot preset
     * 
     * @param id Database id of the preset record
     */
    deleteTimeslotPreset(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a single talk preset by id
     * 
     * @param id Database id of the preset record
     */
    getTalkPreset(id: number, extraHttpRequestParams?: any): Observable<TalkPresetViewModel>;

    /**
     * List all talk presets
     * 
     */
    getTalkPresets(extraHttpRequestParams?: any): Observable<Array<TalkPresetViewModel>>;

    /**
     * Get a single timeslot preset by id
     * 
     * @param id Database id of the preset record
     */
    getTimeslotPreset(id: number, extraHttpRequestParams?: any): Observable<TimeslotPresetViewModel>;

    /**
     * List all timeslot presets
     * 
     */
    getTimeslotPresets(extraHttpRequestParams?: any): Observable<Array<TimeslotPresetViewModel>>;

    /**
     * Update an existing talk preset
     * 
     * @param id Database id of the preset record
     * @param talkPresetRequest 
     */
    updateTalkPreset(id: number, talkPresetRequest: TalkPresetRequest, extraHttpRequestParams?: any): Observable<TalkPresetViewModel>;

    /**
     * Update an existing timeslot preset
     * 
     * @param id Database id of the preset record
     * @param timeslotPresetRequest 
     */
    updateTimeslotPreset(id: number, timeslotPresetRequest: TimeslotPresetRequest, extraHttpRequestParams?: any): Observable<TimeslotPresetViewModel>;

}
