/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExplanationRequest { 
    /**
     * The natural-language question about the planning solution
     */
    question: string;
    /**
     * Id of the planning solution to explain. If omitted, the most recent planning solution is used.
     */
    planningSolutionId?: number;
    /**
     * Conversation id returned by a previous call. Pass it to continue the same multi-turn conversation. If omitted, a new conversation is started.
     */
    conversationId?: string;
}

