/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExplanationViewModel { 
    /**
     * The generated answer
     */
    answer: string;
    /**
     * The GenAI model that produced the answer
     */
    model: string;
    /**
     * Id of the planning solution the answer refers to
     */
    planningSolutionId: number;
    /**
     * Conversation id to pass on follow-up questions
     */
    conversationId: string;
}

