/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeslotViewModel } from './timeslot-view-model';
import { ConstraintMatchViewModel } from './constraint-match-view-model';
import { ScoreViewModel } from './score-view-model';


export interface TalkViewModel { 
    id: number;
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
    favorites?: number;
    timeslot?: TimeslotViewModel;
    score?: ScoreViewModel;
    constraintMatches?: Array<ConstraintMatchViewModel>;
}

