/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TalkPresetViewModel { 
    id: number;
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
    /**
     * Expected number of attendees (used against room seats)
     */
    favorites?: number;
    /**
     * Optional pinned start time (ISO-8601 local time, e.g. \"09:00\"). When set and a timeslot with this start time exists, the talk is locked to it during planning; otherwise the preset is ignored.
     */
    timePreset?: string;
    /**
     * Optional pinned room name. Only honored together with timePreset, and only when a timeslot with the matching start time and room exists; otherwise the preset is ignored.
     */
    roomPreset?: string;
    /**
     * Creation timestamp (ISO-8601), read-only
     */
    created?: string;
    /**
     * Last modification timestamp (ISO-8601), read-only
     */
    updated?: string;
    /**
     * User who created the preset, read-only
     */
    createdBy?: string;
    /**
     * User who last modified the preset, read-only
     */
    updatedBy?: string;
}

