/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TalkPresetViewModel { 
    id: number;
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
    favorites?: number;
    /**
     * Creation timestamp (ISO-8601), read-only
     */
    created?: string;
    /**
     * Last modification timestamp (ISO-8601), read-only
     */
    updated?: string;
    /**
     * User who created the preset, read-only
     */
    createdBy?: string;
    /**
     * User who last modified the preset, read-only
     */
    updatedBy?: string;
}

