/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TalkPresetRequest { 
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
    favorites?: number;
    /**
     * Optional pinned start time (ISO-8601 local time, e.g. \"09:00\"). When set and a timeslot with this start time exists, the talk is locked to it during planning; otherwise the preset is ignored.
     */
    timePreset?: string;
    /**
     * Optional pinned room name. Only honored together with timePreset, and only when a timeslot with the matching start time and room exists; otherwise the preset is ignored.
     */
    roomPreset?: string;
}

