/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeslotViewModel } from './timeslot-view-model';
import { ConstraintMatchViewModel } from './constraint-match-view-model';
import { ScoreViewModel } from './score-view-model';


export interface TalkViewModel { 
    id: number;
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
    favorites?: number;
    /**
     * The pinned start time this talk was planned with (ISO-8601 local time, e.g. \"09:00\"), or absent if the talk was not pinned.
     */
    timePreset?: string;
    /**
     * The pinned room name this talk was planned with, or absent if no room was pinned.
     */
    roomPreset?: string;
    timeslot?: TimeslotViewModel;
    score?: ScoreViewModel;
    constraintMatches?: Array<ConstraintMatchViewModel>;
}

