/**
 * Conference Schedule Optimizer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TalkPresetRequest { 
    title: string;
    speaker?: string;
    durationMinutes?: number;
    beamerRequired?: boolean;
    flipchartRequired?: boolean;
}

